/* test identifier length */
int JS_GENERATOR_STATE_SUSPENDED_YIELD = 1;
int JS_GENERATOR_STATE_SUSPENDED_YIELD_STAR = 2;
int main(void) { return JS_GENERATOR_STATE_SUSPENDED_YIELD + JS_GENERATOR_STATE_SUSPENDED_YIELD_STAR; }
